name: Auto Update Banner and Commit

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    env:
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.4'

    - name: Pull latest changes
      run: git pull origin main

    - name: Install dependencies
      run: npm install

    - name: Run npm script
      run: npm run dev

    - name: Check for changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git diff --exit-code || (git add . && git commit -m "chore: youtube banner updated" && git push)
